site_name: Equinox
nav:
  - Home: index.md
  - Guide:
    - About: guide/about.md
    - Installation: guide/installation.md
    - Workflow: guide/workflow.md
  - Downloads: downloads.md

theme: 
  name: material
  font: false
  palette:
    scheme: slate
    primary: custom

  logo: assets/logo.png

extra:
  homepage: https://example.com

extra_css:
  - stylesheets/extra.css
