site_name: Equinox Manual
theme: 
  name: material
  palette:
    scheme: slate
    primary: custom
    accent: custom
  features:
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
  logo: brand/logo-medium.png

nav:
  - Home: index.md
  - About: guide/about.md
  - Guide:
    - Installation: guide/installation.md
    - Workflow: guide/workflow.md
    - Scenes: guide/scenes.md
    - Effects: guide/effects.md
    - Compositing: guide/compositing.md
    - Grading: guide/grading.md
    - Macros: guide/macros.md
    - External control: guide/devices.md
    - Output: guide/output.md
    - Exports: guide/export.md
  - Effects:
    - Filters: effects/Filters.md
    - Post: effects/Post.md
    - Stylize: effects/Stylize.md
  - Downloads: downloads.md
  - Release notes: changelog.md
  - Contact: contact.md

markdown_extensions:
  - attr_list
  - md_in_html
  - footnotes
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
          
extra:
  homepage: ""
  social:
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/pareidolia.collective/
    - icon: fontawesome/brands/discord
      link: https://discord.gg/WBNr8h6ac3

copyright: Copyright Â© 2026 PAREIDOLIA

extra_css:
  - stylesheets/extra.css
